name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: 'Pamela Perez'
      - name: get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

